version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
      - run: ssh -oStrictHostKeyChecking=no -v root@$159.89.239.206 "./deploy.sh"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy.sh"
workflows:
  build-and-deploy:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch