version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build

  deploy:
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v root@$159.89.239.206 "./deploy.sh"
workflows:
    build-and-test:
      jobs:
        - build-and-test
    deploy:
      jobs:
        - deploy