version: 2
jobs:
  build-test:
    machine:
      enabled: trie
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch