version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
      - run: ssh -oStrictHostKeyChecking=no -v root@$159.89.239.206 "./deploy.sh"
workflows:
    build-test-deploy:
      jobs:
        - build-test-deploy
    deploy:
      jobs:
        - deploy